//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/aspect jimu/BaseWidgetPanel jimu/BaseWidgetFrame jimu/utils ./FoldableDijit ./FoldableWidgetFrame".split(" "),function(p,g,b,d,l,q,r,s,f,t,u){function e(){return b.getMarginBox(jimuConfig.layoutId).w<=m?!0:!1}function h(){return b.getMarginBox(jimuConfig.layoutId).w<=m?"100%":360}var m=jimuConfig.widthBreaks[0],n=b.getMarginBox(jimuConfig.layoutId).h;return p([r,t],{baseClass:"jimu-widget-panel jimu-foldable-dijit jimu-foldable-panel",
closeTolerance:30,startup:function(){this.titleHeight=35;this.isFull=null;this.inherited(arguments);this.createCloseBtn();this.createFoldableBtn();this.resize()},getFullPosition:function(){var a=this.position;this.isFull&&(a.right=0,a.bottom=0);return a},changePosition:function(){var a;this.position.width=h();this.isFull?(b.place(this.domNode,jimuConfig.layoutId),a={left:0,right:0,top:0,bottom:0,width:"auto",height:"auto"}):(b.place(this.domNode,jimuConfig.mapId),a=this.position);b.setStyle(this.domNode,
f.getPositionStyle(a));f.setVerticalCenter(this.titleNode);this.setBorderRadius();this.moveTitle()},setBorderRadius:function(){b.setStyle(this.domNode,this.isFull?{borderTopLeftRadius:0,borderTopRightRadius:0,borderBottomLeftRadius:0,borderBottomRightRadius:0}:{borderTopLeftRadius:"4px",borderTopRightRadius:"4px",borderBottomLeftRadius:"4px",borderBottomRightRadius:"4px"})},_changePos:function(){this.position.width=h();this.position.height="auto"},resize:function(){this._changePos();var a;if(!(a=
this.isFull!==e())){a=b.getMarginBox(jimuConfig.layoutId);var k=n!==a.h;n=a.h;a=k}a&&(this.isFull=e(),this.changePosition(),this.isFull?(b.addClass(this.foldableNode,"fold-down"),b.removeClass(this.foldableNode,"fold-up")):(b.removeClass(this.foldableNode,"fold-down"),b.addClass(this.foldableNode,"fold-up")));a=h();b.setStyle(this.domNode,{width:"number"===typeof a?a+"px":a});this.inherited(arguments);1<this.getChildren().length&&this._setFrameSize()},reloadWidget:function(a){this.inherited(arguments);
this.isWidgetInPanel(a)&&(Array.isArray(this.config.widgets)||this.setTitleLabel(a.label))},updateConfig:function(a){this.inherited(arguments);this.setTitleLabel(a.label)},_setFrameSize:function(){var a,k=b.getContentBox(this.containerNode),c=0;d.forEach(this.getChildren(),function(a){a.folded||c++},this);a=(k.h-(this.getChildren().length-c)*this.getChildren()[0].titleHeight)/c;d.forEach(this.getChildren(),function(c){c.folded?b.setStyle(c.domNode,{height:c.titleHeight+"px"}):b.setStyle(c.domNode,
{height:a+"px"});c.resize()},this)},createCloseBtn:function(){this.closeNode=b.create("div",{"class":"close-btn jimu-vcenter jimu-float-trailing"},this.titleNode);this.own(l(this.closeNode,"click",g.hitch(this,function(a){a.stopPropagation();this.panelManager.closePanel(this)})));f.setVerticalCenter(this.titleNode)},createFoldableBtn:function(){this.foldableNode=b.create("div",{"class":"foldable-btn jimu-vcenter jimu-float-trailing"},this.titleNode);this.own(l(this.foldableNode,"click",g.hitch(this,
function(a){a.stopPropagation();this.onTitleClick()})))},createFrame:function(a){this.config.widgets&&1===this.config.widgets.length||!this.config.widgets?a=new s:(a=new u({label:a.label,widgetManager:this.widgetManager}),q.after(a,"onFoldStateChanged",g.hitch(this,function(){var a=0;this._setFrameSize();d.forEach(this.getChildren(),function(b){b.folded||a++},this);d.forEach(this.getChildren(),function(b){b.foldEnable=!b.folded&&1===a?!1:!0},this)})));return a},createFullCloseTip:function(){return b.create("div",
{"class":"close-tip",innerHTML:"Close",style:{height:this.titleHeight+"px",lineHeight:this.titleHeight+"px"}},this.domNode)},onTitleClick:function(){this.folded?(this.folded=!1,b.setStyle(this.domNode,f.getPositionStyle(this.getFullPosition())),this.moveTitle(),e()?(b.removeClass(this.foldableNode,"fold-up"),b.addClass(this.foldableNode,"fold-down")):(b.addClass(this.foldableNode,"fold-up"),b.removeClass(this.foldableNode,"fold-down"))):(this.folded=!0,b.setStyle(this.domNode,{height:this.titleHeight+
"px"}),this.moveTitle(),e()?(b.removeClass(this.foldableNode,"fold-down"),b.addClass(this.foldableNode,"fold-up")):(b.addClass(this.foldableNode,"fold-down"),b.removeClass(this.foldableNode,"fold-up")));this.onFoldStateChanged()},onOpen:function(){this.inherited(arguments);this._changePos();this.isFull=e();this.changePosition();if(this.folded)this.onTitleClick()},onFoldStateChanged:function(){d.forEach(this.getChildren(),function(a){(a=a.getWidget())&&(this.folded?this.widgetManager.minimizeWidget(a):
this.widgetManager.maximizeWidget(a))},this)},moveTitle:function(){this.isFull?this.folded?b.setStyle(this.domNode,{top:b.getMarginBox(jimuConfig.layoutId).h-this.titleHeight+"px"}):b.setStyle(this.domNode,{top:"0px"}):b.setStyle(this.domNode,{top:this.position.top+"px"})}})});