//>>built
require({cache:{"url:widgets/LayerList/LayerListView.html":'\r\n\r\n\x3ctable class\x3d"layer-list-table"\x3e\r\n  \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"layerListTable"\x3e\x3c/tbody\x3e\r\n  \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"tableListTable"\x3e\x3c/tbody\x3e       \r\n\x3c/table\x3e\r\n'}});
define("dijit/_WidgetBase dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/dom-construct dojo/on dojo/query jimu/dijit/CheckBox ./PopupMenu dijit/_TemplatedMixin dojo/text!./LayerListView.html jimu/dijit/LoadingIndicator dojo/dom-attr dojo/dom-class dojo/dom-style ./NlsStrings".split(" "),function(t,u,m,n,r,e,p,f,v,w,x,y,z,s,k,l,A){return u([t,x],{templateString:y,_currentSelectedLayerRowNode:null,postMixInProperties:function(){this.inherited(arguments);this.nls=A.value},postCreate:function(){n.forEach(this.operLayerInfos.finalLayerInfos,
function(a){this.drawListNode(a,0,this.layerListTable,!0)},this);n.forEach(this.operLayerInfos.tableInfos,function(a){this.drawListNode(a,0,this.tableListTable,!0)},this)},drawListNode:function(a,b,c){var d;0===a.newSubLayers.length?(d=this.addLayerNode(a,b,c),this.config.showLegend?this.addLegendNode(a,b,d.subNode):l.set(f(".showLegend-image",d.currentNode)[0],"display","none")):(d=this.addLayerNode(a,b,c),n.forEach(a.newSubLayers,m.hitch(this,function(a,b){this.drawListNode(b,a+1,d.subNode)},b)))},
addLayerNode:function(a,b,c){var d=e.create("tr",{"class":"jimu-widget-row layer-row ",layerTrNodeId:a.id},c),g,h,f,k,n,q;g=e.create("td",{"class":"col col1"},d);for(f=0;f<b;f++)e.create("div",{"class":"begin-blank-div jimu-float-leading",innerHTML:""},g);q=e.create("div",{"class":"showLegend-div jimu-float-leading"},g);k=e.create("img",{"class":"showLegend-image jimu-leading-margin1",src:isRTL?this.layerListWidget.folderUrl+"images/v_left.png":this.layerListWidget.folderUrl+"images/v_right.png",
alt:"l"},q);h=e.create("div",{"class":"div-select jimu-float-leading jimu-leading-margin1 jimu-trailing-margin1"},g);f=new v({checked:a.isVisible()});e.place(f.domNode,h);n=e.create("div",{"class":"noLegend-div jimu-float-leading"},g);e.create("img",{"class":"noLegend-image",src:this.layerListWidget.folderUrl+(a.isTable?"images/table.png":"images/noLegend.png"),alt:"l"},n);if(a.noLegend||a.isTable)l.set(q,"display","none"),l.set(h,"display","none"),l.set(n,"display","block");l.set(g,"width",12*b+
35+"px");b=e.create("td",{"class":"col col2"},d);e.create("div",{innerHTML:a.title,"class":"div-content jimu-float-leading"},b);g=e.create("td",{"class":"col col3"},d);g=e.create("div",{"class":"layers-list-popupMenu-div"},g);h=(new w({_layerInfo:a,box:this.layerListWidget.domNode.parentNode,_appConfig:this.layerListWidget.appConfig})).placeAt(g);this.own(p(h,"onMenuClick",m.hitch(this,this._onPopupMenuItemClick,a,h)));h.loading=new z({hidden:!0});h.loading.placeAt(g);c=e.create("tr",{"class":"",
layerContentTrNodeId:a.id},c);c=e.create("td",{"class":"",colspan:"3"},c);c=e.create("table",{"class":"layer-sub-node"},c);this.own(p(b,"click",m.hitch(this,this._onRowTrClick,a,k,d,c)));this.own(p(q,"click",m.hitch(this,this._onRowTrClick,a,k,d,c)));this.own(p(d,"mouseover",m.hitch(this,this._onLayerNodeMouseover,d,h)));this.own(p(d,"mouseout",m.hitch(this,this._onLayerNodeMouseout,d,h)));this.own(p(f.domNode,"click",m.hitch(this,this._onCkSelectNodeClick,a,f)));this.own(p(g,"click",m.hitch(this,
this._onPopupMenuClick,a,h,d)));return{currentNode:d,subNode:c}},addLegendNode:function(a,b,c){c=e.create("tr",{"class":"legend-node-tr"},c);c=e.create("td",{"class":"legend-node-td"},c);try{var d=a.createLegendsNode();l.set(d,"font-size",12*(b+1)+"px");e.place(d,c)}catch(g){console.error(g)}},_fold:function(a,b,c){"none"===l.get(c,"display")?(l.set(c,"display","table"),s.set(b,"src",this.layerListWidget.folderUrl+"images/v.png"),a=!1):(l.set(c,"display","none"),s.set(b,"src",isRTL?this.layerListWidget.folderUrl+
"images/v_left.png":this.layerListWidget.folderUrl+"images/v_right.png"),a=!0);return a},_onCkSelectNodeClick:function(a,b,c){b.checked?a.setTopLayerVisible(!0):a.setTopLayerVisible(!1);c.stopPropagation()},_onPopupMenuClick:function(a,b,c,d){b.btnClick();this._changeSelectedLayerRow(c);b&&"opened"===b.state?b.closeDropMenu():(this._hideCurrentPopupMenu(),b.loading.show(),b&&(this.currentPopupMenu=b,b.getPopupMenuInfo().then(m.hitch(this,function(d){var c=f("[itemid\x3dcontrolPopup]",b.dropMenuNode)[0];
c&&a.controlPopupInfo&&(a.controlPopupInfo.enablePopup?r.setAttr(c,"innerHTML",this.nls.removePopup):r.setAttr(c,"innerHTML",this.nls.enablePopup));b.openDropMenu(d.getDeniedItems());b.loading.hide()}))));d.stopPropagation()},_hideCurrentPopupMenu:function(){this.currentPopupMenu&&"opened"===this.currentPopupMenu.state&&this.currentPopupMenu.closeDropMenu()},_onLayerNodeMouseover:function(a,b){k.add(a,"layer-row-mouseover");b&&k.add(b.btnNode,"jimu-icon-btn-selected")},_onLayerNodeMouseout:function(a,
b){k.remove(a,"layer-row-mouseover");b&&k.remove(b.btnNode,"jimu-icon-btn-selected")},_onPopupMenuHide:function(){console.log("aaa")},_onLayerListWidgetPaneClick:function(a){a&&a.closeDropMenu()},_onRowTrClick:function(a,b,c,d){this._changeSelectedLayerRow(c);b=this._fold(a,b,d);a.isLeaf()&&!b&&(d=f(".legends-div",d)[0],b=f(".legends-loading-img",d)[0],d&&b&&a.drawLegends(d,this.layerListWidget.appConfig.portalUrl))},_changeSelectedLayerRow:function(a){this._currentSelectedLayerRowNode&&this._currentSelectedLayerRowNode===
a||(this._currentSelectedLayerRowNode&&k.remove(this._currentSelectedLayerRowNode,"jimu-widget-row-selected"),k.add(a,"jimu-widget-row-selected"),this._currentSelectedLayerRowNode=a)},_onPopupMenuItemClick:function(a,b,c,d){d={itemKey:c.key,extraData:d,layerListWidget:this.layerListWidget,layerListView:this};"transparency"===c.key?"none"===l.get(b.transparencyDiv,"display")?b.showTransNode(a.getOpacity()):b.hideTransNode():(a=b.popupMenuInfo.onPopupMenuClick(d),a.closeMenu&&b.closeDropMenu())},_exchangeLayerTrNode:function(a,
b){var c=f("tr[layerTrNodeId\x3d'"+a+"']",this.layerListTable)[0],d=f("tr[layerTrNodeId\x3d'"+b+"']",this.layerListTable)[0],e=f("tr[layerContentTrNodeId\x3d'"+b+"']",this.layerListTable)[0];this.layerListTable.removeChild(d);this.layerListTable.insertBefore(d,c);this.layerListTable.removeChild(e);this.layerListTable.insertBefore(e,c)},moveUpLayer:function(a){var b=this.operLayerInfos.moveUpLayer(a);b&&this._exchangeLayerTrNode(b,a)},moveDownLayer:function(a){var b=this.operLayerInfos.moveDownLayer(a);
b&&this._exchangeLayerTrNode(a,b)}})});