//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/Deferred dojo/promise/all jimu/portalUrlUtils jimu/WidgetManager ./NlsStrings".split(" "),function(l,g,d,k,m,h,n,p){var f=l([],{_candidateMenuItems:null,_displayItems:null,_layerInfo:null,_layerType:null,_appConfig:null,constructor:function(a,b,c,d){this.nls=p.value;this._layerInfo=a;this._layerType=c;this._appConfig=d;this._initCandidateMenuItems();this._initDisplayItems(b)},_getATagLabel:function(){var a,b;(a=this._layerInfo._isItemLayer&&
this._layerInfo._isItemLayer())?(a=h.getItemDetailsPageUrl(h.getStandardPortalUrl(this._appConfig.portalUrl),a),b=this.nls.itemShowItemDetails):this._layerInfo.layerObject&&this._layerInfo.layerObject.url&&("CSVLayer"===this._layerType||"KMLLayer"===this._layerType)?(a=this._layerInfo.layerObject.url,b=this.nls.itemDownload):(a=this._layerInfo.layerObject&&this._layerInfo.layerObject.url?this._layerInfo.layerObject.url:"",b=this.nls.itemDesc);return'\x3ca class\x3d"menu-item-description" target\x3d"_blank" href\x3d"'+
a+'"\x3e'+b+"\x3c/a\x3e"},_initCandidateMenuItems:function(){this._candidateMenuItems=[{key:"separator",label:""},{key:"empty",label:this.nls.empty},{key:"zoomto",label:this.nls.itemZoomTo},{key:"transparency",label:this.nls.itemTransparency},{key:"moveup",label:this.nls.itemMoveUp},{key:"movedown",label:this.nls.itemMoveDown},{key:"table",label:this.nls.itemToAttributeTable},{key:"controlPopup",label:this.nls.removePopup},{key:"url",label:this._getATagLabel()}]},_initDisplayItems:function(a){this._displayItems=
[];g.forEach(a,function(a){g.forEach(this._candidateMenuItems,function(c){a.key===c.key&&(this._displayItems.push(d.clone(c)),a.onClick&&(this._displayItem.onClick=a.onClick))},this)},this)},getDeniedItems:function(){var a=new k,b=[];this._layerInfo.isFirst?b.push("moveup"):this._layerInfo.isLast&&b.push("movedown");(!this._layerInfo.layerObject||!this._layerInfo.layerObject.url)&&b.push("url");var c=this._layerInfo.loadInfoTemplate(),f=this._layerInfo.getSupportTableInfo();m({infoTemplate:c,supportTableInfo:f}).then(d.hitch(this._layerInfo,
function(c){c.infoTemplate||b.push("controlPopup");c=c.supportTableInfo;var e=n.getInstance().getWidgetsByName("AttributeTable");(!(0<e.length&&e[0].visible)||!c.isSupportedLayer||!c.isSupportQuery)&&b.push("table");a.resolve(b)}),function(){a.resolve(b)});return a},getDisplayItems:function(){return this._displayItems},onPopupMenuClick:function(a){var b={closeMenu:!0};switch(a.itemKey){case "zoomto":this._onItemZoomToClick(a);break;case "moveup":this._onMoveUpItemClick(a);break;case "movedown":this._onMoveDownItemClick(a);
break;case "table":this._onTableItemClick(a);break;case "transparencyChanged":this._onTransparencyChanged(a);b.closeMenu=!1;break;case "controlPopup":this._onControlPopup()}return b},_onItemZoomToClick:function(a){this._layerInfo.getExtent().then(d.hitch(this,function(a){this._layerInfo.map.setExtent(a[0])}))},_onMoveUpItemClick:function(a){this._layerInfo.isFirst||a.layerListView.moveUpLayer(this._layerInfo.id)},_onMoveDownItemClick:function(a){this._layerInfo.isLast||a.layerListView.moveDownLayer(this._layerInfo.id)},
_onTableItemClick:function(a){this._layerInfo.getLayerType().then(d.hitch(this,function(b){0<=this._layerInfo._getLayerTypesOfSupportTable().indexOf(b)&&a.layerListWidget.publishData({target:"AttributeTable",layer:this._layerInfo})}))},_onTransparencyChanged:function(a){this._layerInfo.setOpacity(1-a.extraData.newTransValue)},_onControlPopup:function(a){this._layerInfo.controlPopupInfo.enablePopup?this._layerInfo.disablePopup():this._layerInfo.enablePopup();this._layerInfo.map.infoWindow.hide()}});
f.create=function(a,b){var c=new k,g=a.isRootLayer(),h={RootLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"moveup"},{key:"movedown"},{key:"separator"},{key:"url"}],RootLayerAndFeatureLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"controlPopup"},{key:"separator"},{key:"moveup"},{key:"movedown"},{key:"separator"},{key:"table"},{key:"separator"},{key:"url"}],FeatureLayer:[{key:"controlPopup"},{key:"separator"},{key:"table"},{key:"separator"},{key:"url"}],GroupLayer:[{key:"url"}],
Table:[{key:"table"},{key:"separator"},{key:"url"}],"default":[{key:"url",onClick:null}]};a.getLayerType().then(d.hitch(this,function(e){var d="",d=g&&("FeatureLayer"===e||"CSVLayer"===e||"ArcGISImageServiceLayer"===e)?"RootLayerAndFeatureLayer":g?"RootLayer":"FeatureLayer"===e||"CSVLayer"===e?"FeatureLayer":"GroupLayer"===e?"GroupLayer":"Table"===e?"Table":"default";c.resolve(new f(a,h[d],e,b))}),d.hitch(this,function(){c.resolve(new f(a,[{key:"empty"}]))}));return c};return f});