//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define(["dojo/_base/lang","dojo/_base/array","jimu/LayerInfos/LayerInfos","dojo/Deferred","dojo/promise/all"],function(g,k,t,p,b){function u(a){var e=[],b=[];k.forEach(a,function(h){0>e.indexOf(h.name)?e.push(h.name):b.push(h)});k.forEach(b,function(h){h.name=h.name+"-"+h.id})}var n={readLayerInfosObj:function(a){return t.getInstance(a,a.itemInfo)},readLayerInfosFromMap:function(a){var b=new p;t.getInstance(a,a.itemInfo).then(g.hitch(this,
function(a){var h=[];a.traversal(g.hitch(this,function(a){h.push(a)}));a=a.getTableInfoArray();h=h.concat(a);b.resolve(h)}),g.hitch(this,function(a){console.error(a);b.reject(a)}));return b.promise},readLayerObjectsFromMap:function(a){var e=new p,l=[];this.readLayerInfosFromMap(a).then(g.hitch(this,function(a){k.forEach(a,g.hitch(this,function(a){l.push(a.getLayerObject())}));b(l).then(g.hitch(this,function(a){e.resolve(a)}),g.hitch(this,function(a){e.reject(a);console.error(a)}))}),g.hitch(this,
function(a){e.reject(a)}));return e.promise},readSupportTableInfoFromLayerInfos:function(a){var e=new p,l=[];k.forEach(a,g.hitch(this,function(a){l.push(a.getSupportTableInfo())}));b(l).then(g.hitch(this,function(b){b=g.clone(b);k.forEach(b,function(b,e){b.id=a[e].id});e.resolve(b)}),function(a){e.reject(a)});return e.promise},readConfigLayerInfosFromMap:function(a){var e=new p,l=[];this.readLayerInfosFromMap(a).then(g.hitch(this,function(a){var m=[];k.forEach(a,function(a){l.push(a.getSupportTableInfo())});
b(l).then(g.hitch(this,function(b){k.forEach(b,g.hitch(this,function(b,e){b.isSupportedLayer&&(a[e].name=a[e].title,m.push(a[e]))}));u(m);e.resolve(m)}),g.hitch(this,function(a){e.reject(a)}))}),g.hitch(this,function(a){e.reject(a)}));return e.promise},getConfigInfosFromLayerInfos:function(a){return k.map(a,function(a){return n.getConfigInfoFromLayerInfo(a)})},getConfigInfoFromLayerInfo:function(a){var b={};b.name=a.name||a.title;b.id=a.id;b.show=a.isShowInMap();b.layer={url:a.getUrl()||a.layerObject&&
a.layerObject.url};if((a=a.getPopupInfo())&&!a.description)b.layer.fields=k.map(a.fieldInfos,function(a){return{name:a.fieldName,alias:a.label.toLowerCase(),show:a.visible}});return b}};return n})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"firstPage" class\x3d"first-page"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"tableEditInfosError" style\x3d"display:none"\x3e\x3c/div\x3e\r\n    \x3cdiv style\x3d"margin: 10px;" data-dojo-attach-point\x3d"exportcsv" checked \r\n          data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:15px; width: 100%; height: 100%;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .first-page{position: relative; height: 100%;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; position: absolute; top: 0; bottom: 36px;}.jimu-widget-attributetable-setting .export-csv{margin: 10px; position: absolute; bottom: 0;}",
"*now":function(g){g(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","el","es","et","fi","fr","he","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sv","th","tr","zh-cn","vi","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/dom-style dojo/query jimu/dijit/Message jimu/dijit/LoadingShelter ../utils dijit/TooltipDialog dijit/popup".split(" "),function(g,k,t,p,b,u,n,a,e,l,h,m,v,q,w,r){return g([t,k],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,tooltipDialogs:{},fieldTables:{},_allLayerFields:null,_layerInfos:null,_tableInfos:null,
_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new p({fields:[{name:"label",title:this.nls.label,width:"40%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},{name:"index",title:"index",
type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"40%",actions:["edit"],"class":"symbol"},{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);u.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.displayFieldsTable.startup();this.shelter=new v({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();
this.shelter.show();q.readLayerInfosObj(this.map).then(b.hitch(this,function(s){this.own(s.on("layerInfosChanged",b.hitch(this,this.onLayerInfosChanged)));this.own(a(this.displayFieldsTable,"actions-edit",b.hitch(this,this.editFieldsClick)));this.own(a(this.displayFieldsTable,"row-click",b.hitch(this,this._verifiedOnShowClick)));this.own(a(this.getParent().getParent().domNode,"click",b.hitch(this,function(){r.close()})));u.addClass(this.exportcsv.domNode,"export-csv");this.setConfig(this.config)}))},
editFieldsClick:function(a){var f=h(".action-item-parent",a);if(f&&f.length)if(f=this.displayFieldsTable.getRowData(a),f.show){var c=parseInt(f.index,10);this.shelter.show();this._getLayerFields(c).then(b.hitch(this,function(f){this.openFieldsDialog(a,f,c)}),b.hitch(this,function(a){console.error(a)})).always(b.hitch(this,function(){this.shelter.hide()}))}else var d=new m({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:b.hitch(this,function(){d.close()})}]})},_verifiedOnShowClick:function(a){var f=
this.displayFieldsTable.getRowData(a),c=parseInt(f.index,10),b=null,b=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[c]:this._layerInfos[c],c=-1<this._unSpportQueryCampsite.layerNames.indexOf(b.name||b.title);f.show&&c&&(new m({message:this.nls.unsupportQueryWarning}),f.show=!1,this.displayFieldsTable.editRow(a,f))},_getLayerFields:function(a){var f=new e,c=this._allLayerFields[a];c?f.resolve(c):this._layerInfos[a].getLayerObject().then(b.hitch(this,function(a){a.fields?
f.resolve(a.fields):f.reject()}),b.hitch(this,function(a){f.reject(a)}));return f},openFieldsDialog:function(s,f,c){if(!this.tooltipDialogs[c]){var d=this._createFieldsTable(f,c);this.currentFieldTable=d;this.fieldTables[c]=d;this.own(a(d,"row-click",b.hitch(this,function(a){var c=d.getData();if(!n.some(c,b.hitch(this,function(a){return a.show}))&&(new m({message:this.nls.fieldCheckWarning}),c=d.getRowData(a)))c.show=!0,d.editRow(a,c)})));f=new w({style:"width: 400px;height:300px;",content:d.domNode,
onClose:b.hitch(this,function(){this._allLayerFields[c]=d.getData()}),onCancel:b.hitch(this,function(){r.close()})});this.tooltipDialogs[c]=f}s=h(".row-edit-div",s)[0];r.open({parent:this,popup:this.tooltipDialogs[c],around:s,orient:["before-centered","below","below-alt","above","above-alt"]})},_createFieldsTable:function(a){for(var f=new p({fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show"},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,
editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}}),c=0;c<a.length;c++)a[c].show=void 0===a[c].show?!0:!!a[c].show,f.addRow(a[c]);return f},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this.tooltipDialogs={};this._processTableData().then(b.hitch(this,function(a){this._init(a);this.shelter.hide()}),b.hitch(this,
function(a){new m({message:a.message||a})}))},onLayerInfosChanged:function(a,f,c){"added"!==f||(!c||!a)||c.getSupportTableInfo().then(b.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?this._delayedLayerInfos.push(c):this._layerInfos&&(0<this._layerInfos.length&&!this._getLayerInfoById(c.id))&&(this._delayedLayerInfosAfterInit.push(c),this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var b=
this._layerInfos.length,c=0;c<a.length;c++){var d=q.getConfigInfoFromLayerInfo(a[c]);this.displayFieldsTable.addRow({label:d.name||d.title,url:d.layer.url,index:""+(b+c),show:d.show});this._allLayerFields.push(d.layer.fields);this._layerInfos.push(a[c])}},_processDelayedLayerInfos:function(){0<this._delayedLayerInfos.length&&(n.forEach(this._delayedLayerInfos,b.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=
new e;q.readConfigLayerInfosFromMap(this.map).then(b.hitch(this,function(f){this._layerInfos=f;this._processDelayedLayerInfos();q.readSupportTableInfoFromLayerInfos(this._layerInfos).then(b.hitch(this,function(c){this._tableInfos=c;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?(c=n.filter(this.config.layerInfos,b.hitch(this,function(a){return this._getLayerInfoById(a.id)})),this.config.layerInfos=c,this._unSpportQueryCampsite.fromConfig=!0,this._unSpportQueryCampsite.layerNames=
this._getUnsupportQueryLayerNames(this.config.layerInfos),a.resolve(c)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(q.getConfigInfosFromLayerInfos(f)))}),function(c){console.error(c);a.reject(c)})}),b.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_getUnsupportQueryLayerNames:function(a){var f=[];n.forEach(a,b.hitch(this,function(a){var b=this._getSupportTableInfoById(a.id);b&&!b.isSupportQuery&&
f.push(a.name||a.title)}));return f},_init:function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c].show&&this._getSupportTableInfoById(a[c].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[c].name||a[c].title,url:a[c].layer.url,index:""+c,show:d});this._allLayerFields.push(a[c].layer.fields);this._unSpportQueryCampsite.fromConfig&&(d=(d=this._unSpportQueryCampsite.layerNames)&&-1<d.indexOf(a[c].name||a[c].title),a[c].show&&d&&b.push(a[c].name||a[c].title))}this._unSpportQueryCampsite.fromConfig&&
0<b.length&&new m({message:this.nls.unsupportQueryLayers+"\x3cbr\x3e\x3cbr\x3e"+b.toString()});0===a.length?(l.set(this.tableEditInfosError,"display",""),this.tableEditInfosError.innerHTML=this.nls.noLayers):l.set(this.tableEditInfosError,"display","none");this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check()},_destroyPopupDialog:function(){r.close();for(var a in this.tooltipDialogs)this.tooltipDialogs[a]&&this.tooltipDialogs[a].destroy&&(this.tooltipDialogs[a].destroy(),this.tooltipDialogs[a]=
null)},_getLayerInfoById:function(a){for(var b=0,c=this._layerInfos.length;b<c;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,c=this._tableInfos.length;b<c;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){r.close();var a=this.displayFieldsTable.getData(),f=[],c=a.length;if(this.config&&this.config.layerInfos&&0<this.config.layerInfos.length)n.forEach(a,b.hitch(this,function(b,c){var e=this.config.layerInfos[c],
d={};d.name=e.name||e.title;d.id=e.id;d.layer={};d.layer.url=a[c].url;d.layer.fields=this._allLayerFields[c];d.show=a[c].show;f.push(d)}));else for(var d=0;d<c;d++){var e={};e.name=this._layerInfos[d].name||this._layerInfos[d].title;e.id=this._layerInfos[d].id;e.layer={};e.layer.url=a[d].url;e.layer.fields=this._allLayerFields[d];e.show=a[d].show;f.push(e)}this.config.layerInfos=f;this.exportcsv.getValue()?this.config.hideExportButton=!1:this.config.hideExportButton=!0;return this.config},destroy:function(){this._destroyPopupDialog();
this.inherited(arguments)}})});